apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-websocket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-websocket
  template:
    metadata:
      labels:
        app: golang-websocket
    spec:
      containers:
        - name: golang-websocket
          image: gcr.io/k8s-0529/golang-websocket:v1
          ports:
            - containerPort: 8080
          env:
            - name: "PORT"
              value: "8080"